version: 0.0
os: linux

files:
  - source: ./csye/target/csye-0.0.1-SNAPSHOT.jar
    destination: /

hooks:
  AfterInstall:
  - location: ./codedeploy/afterInstall.sh
    timeout: 180
    runas: ubuntu
  ApplicationStart:
  - location: ./codedeploy/applicationStart.sh
    timeout: 180
    runas: ubuntu
  BeforeInstall:
  - location: ./codedeploy/beforeInstall.sh
    timeout: 180
    runas: ubuntu