version: 0.0
os: linux

files:
  - source: ./
    destination: /home/ubuntu

hooks:
  ApplicationStop:
  - location: ./codedeploy/applicationstop.sh
    timeout: 180
    runas: ubuntu
  ApplicationStart:
  - location: ./codedeploy/applicationstart.sh
    timeout: 180
    runas: ubuntu